import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "atropos/atropos.css";
import {
  Footer,
  FooterSkeleton,
  NavBar,
  NavBarSkeleton,
} from "@/components/layout";
import { getNavBar } from "@/services/getNavBar";
import { getFooter } from "@/services/getFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SSL Distribuciones",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navData = await getNavBar();
  const footerData = await getFooter();
  return (
    <html
      lang="es"
      style={{ colorScheme: "dark", maxWidth: "100vw", overflowX: "hidden" }}
    >
      <body className={[inter.className, "relative bg-black"].join(" ")}>
        <div className="w-full">
          <div
            className="absolute inset-0 -z-10"
            style={{
              background:
                "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(120, 180, 255, 0.25), transparent 70%), transparent",
            }}
          />

          <div
            className="absolute inset-0 -z-10"
            style={{
              backgroundImage: `
          radial-gradient(circle at 50% 65%, 
            rgba(120, 180, 255, 0.15) 0%, 
            rgba(120, 180, 255, 0.15) 5%, 
            rgba(120, 180, 255, 0.15) 10%, 
            transparent 50%
          )
        `,
            }}
          />

          {navData ? <NavBar {...navData} /> : <NavBarSkeleton />}
          {children}
          {footerData ? <Footer {...footerData} /> : <FooterSkeleton />}
        </div>
      </body>
    </html>
  );
}
