import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/layout/navbar/NavBar";
import "atropos/atropos.css";
import NavBarSkeleton from "@/components/layout/navbar/NavBarSkeleton";
import { NavBarData } from "@/components/layout/navbar/types";
import { AppProvider } from "@/context";
import { Footer, FooterSkeleton } from "@/components/layout/footer";
import { getData } from "@/services/services";
import { FooterData } from "@/components/layout/footer/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SSL Distribuciones",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navData: NavBarData | undefined = await getData(
    "navbar?populate[logo][populate]=*&populate[menu][populate][menuItem][populate]=*",
    "ui"
  );
  const footerData: FooterData | undefined = await getData(
    "footer?populate[logo][populate]=*&populate[menu][populate][menuItem][populate]=*&populate[mediaLinks][populate]=*",
    "ui"
  );
  return (
    <html
      lang="es"
      style={{ colorScheme: "dark", maxWidth: "100vw", overflowX: "hidden" }}
    >
      <body className={[inter.className, "relative"].join(" ")}>
        <AppProvider>
          {navData ? <NavBar {...navData} /> : <NavBarSkeleton />}
          {children}
          {footerData ? <Footer {...footerData} /> : <FooterSkeleton />}
        </AppProvider>
      </body>
    </html>
  );
}
